/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: CategoryReference;
  author?: AuthorReference;
  publishedAt?: string;
  featured?: boolean;
  readTime?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | CategoryReference
  | AuthorReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../frontend/lib/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featured,    readTime,    coverImage {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    },    category->{ _id, title, "slug": slug.current },    author->{ _id, name, bio, image { asset->{ url } } }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    bio: string | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../frontend/lib/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    body,    publishedAt,    featured,    readTime,    coverImage {      asset->{ _id, url, metadata { lqip, dimensions } },      alt,      hotspot,      crop    },    category->{ _id, title, "slug": slug.current },    author->{ _id, name, bio, image { asset->{ url } } }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    bio: string | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../frontend/lib/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)][].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../frontend/lib/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc){    _id,    title,    "slug": slug.current  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    featured,\n    readTime,\n    coverImage {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    },\n    category->{ _id, title, "slug": slug.current },\n    author->{ _id, name, bio, image { asset->{ url } } }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    body,\n    publishedAt,\n    featured,\n    readTime,\n    coverImage {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      alt,\n      hotspot,\n      crop\n    },\n    category->{ _id, title, "slug": slug.current },\n    author->{ _id, name, bio, image { asset->{ url } } }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)][].slug.current\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current\n  }\n': CATEGORIES_QUERY_RESULT;
  }
}
