name: CI

on:
#  push:
#    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Check for code formatting
        run: |
          cd frontend
          npm run lint
      - name: Build the project
        run: |
          cd frontend
          npm run build